# -*- coding: utf-8 -*-
"""FINAL DS PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddYC1_3pgi18vryDrGxh8kHqVZNxFGhv

individual INDOOR_CLEAR images skewness and kurtosis
"""

# prompt: how to find skewness and kurtosis of individual indoor_clear folder

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis
import matplotlib.pyplot as plt

def analyze_images_in_folder(folder_path):
  """
  Calculates skewness and kurtosis for each image in a folder.

  Args:
      folder_path: The path to the folder containing the images.
  """
  if not os.path.exists(folder_path):
    print(f"Error: Folder '{folder_path}' not found.")
    return

  for filename in os.listdir(folder_path):
    if filename.endswith(('.jpg', '.jpeg', '.png')):  # Add other image extensions if needed
      image_path = os.path.join(folder_path, filename)
      try:
        image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        if image is None:
          print(f"Error: Could not read image '{image_path}'. Skipping.")
          continue

        skewness = skew(image.flatten())
        kurt = kurtosis(image.flatten())

        print(f"Image: {filename}")
        print(f"  Skewness: {skewness}")
        print(f"  Kurtosis: {kurt}")

        # Optional: Display histogram
        # hist, bins = np.histogram(image.flatten(), 100, [0, 256]) # Adjust range if needed
        # plt.hist(image.flatten(), bins=100, range=[0, 256], density=True, color='blue') # Adjust range if needed
        # plt.title(f'Histogram of {filename}')
        # plt.xlabel('Pixel Intensity')
        # plt.ylabel('Normalized Frequency')
        # plt.show()

      except Exception as e:
        print(f"Error processing image '{image_path}': {e}")

# Example usage:
analyze_images_in_folder("/content/drive/MyDrive/INDOOR_CLEAR/clear") # Replace with your actual folder path

"""individual INDOOR_HAZY images skewness and kurtosis"""

# prompt: how to find skewness and kurtosis of individual indoor_hazy folder

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis
import matplotlib.pyplot as plt

def analyze_images_in_folder(folder_path):
  """
  Calculates skewness and kurtosis for each image in a folder.

  Args:
      folder_path: The path to the folder containing the images.
  """
  if not os.path.exists(folder_path):
    print(f"Error: Folder '{folder_path}' not found.")
    return

  for filename in os.listdir(folder_path):
    if filename.endswith(('.jpg', '.jpeg', '.png')):  # Add other image extensions if needed
      image_path = os.path.join(folder_path, filename)
      try:
        image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        if image is None:
          print(f"Error: Could not read image '{image_path}'. Skipping.")
          continue

        skewness = skew(image.flatten())
        kurt = kurtosis(image.flatten())

        print(f"Image: {filename}")
        print(f"  Skewness: {skewness}")
        print(f"  Kurtosis: {kurt}")

        # Optional: Display histogram
        # hist, bins = np.histogram(image.flatten(), 100, [0, 256]) # Adjust range if needed
        # plt.hist(image.flatten(), bins=100, range=[0, 256], density=True, color='blue') # Adjust range if needed
        # plt.title(f'Histogram of {filename}')
        # plt.xlabel('Pixel Intensity')
        # plt.ylabel('Normalized Frequency')
        # plt.show()

      except Exception as e:
        print(f"Error processing image '{image_path}': {e}")

# Example usage:
analyze_images_in_folder("/content/drive/MyDrive/INDOOR_HAZY/hazy") # Replace with your actual folder path

"""individual OUTDOOR_CLEAR images skewness and kurtosis"""

# prompt: how to find skewness and kurtosis of individual indoor_hazy folder

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis
import matplotlib.pyplot as plt

def analyze_images_in_folder(folder_path):
  """
  Calculates skewness and kurtosis for each image in a folder.

  Args:
      folder_path: The path to the folder containing the images.
  """
  if not os.path.exists(folder_path):
    print(f"Error: Folder '{folder_path}' not found.")
    return

  for filename in os.listdir(folder_path):
    if filename.endswith(('.jpg', '.jpeg', '.png')):  # Add other image extensions if needed
      image_path = os.path.join(folder_path, filename)
      try:
        image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        if image is None:
          print(f"Error: Could not read image '{image_path}'. Skipping.")
          continue

        skewness = skew(image.flatten())
        kurt = kurtosis(image.flatten())

        print(f"Image: {filename}")
        print(f"  Skewness: {skewness}")
        print(f"  Kurtosis: {kurt}")

        # Optional: Display histogram
        # hist, bins = np.histogram(image.flatten(), 100, [0, 256]) # Adjust range if needed
        # plt.hist(image.flatten(), bins=100, range=[0, 256], density=True, color='blue') # Adjust range if needed
        # plt.title(f'Histogram of {filename}')
        # plt.xlabel('Pixel Intensity')
        # plt.ylabel('Normalized Frequency')
        # plt.show()

      except Exception as e:
        print(f"Error processing image '{image_path}': {e}")

# Example usage:
analyze_images_in_folder("/content/drive/MyDrive/OUTDOOR_CLEAR/clear") # Replace with your actual folder path

"""individual OUTDOOR_HAZY images skewness and kurtosis"""

# prompt: how to find skewness and kurtosis of individual indoor_hazy folder

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis
import matplotlib.pyplot as plt

def analyze_images_in_folder(folder_path):
  """
  Calculates skewness and kurtosis for each image in a folder.

  Args:
      folder_path: The path to the folder containing the images.
  """
  if not os.path.exists(folder_path):
    print(f"Error: Folder '{folder_path}' not found.")
    return

  for filename in os.listdir(folder_path):
    if filename.endswith(('.jpg', '.jpeg', '.png')):  # Add other image extensions if needed
      image_path = os.path.join(folder_path, filename)
      try:
        image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        if image is None:
          print(f"Error: Could not read image '{image_path}'. Skipping.")
          continue

        skewness = skew(image.flatten())
        kurt = kurtosis(image.flatten())

        print(f"Image: {filename}")
        print(f"  Skewness: {skewness}")
        print(f"  Kurtosis: {kurt}")

        # Optional: Display histogram
        # hist, bins = np.histogram(image.flatten(), 100, [0, 256]) # Adjust range if needed
        # plt.hist(image.flatten(), bins=100, range=[0, 256], density=True, color='blue') # Adjust range if needed
        # plt.title(f'Histogram of {filename}')
        # plt.xlabel('Pixel Intensity')
        # plt.ylabel('Normalized Frequency')
        # plt.show()

      except Exception as e:
        print(f"Error processing image '{image_path}': {e}")

# Example usage:
analyze_images_in_folder("/content/drive/MyDrive/OUTDOOR_HAZY/hazy") # Replace with your actual folder path

"""line chart of the skewness of INDOOR_CLEAR and INDOOR_HAZY"""

# prompt: how to compare line chart between INDOOR_CLEAR AND INDOOR_HAZY all images with ONLY skewness with INDOOR_CLEAR AND INDOOR_HAZY with up and down line chart

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis
import matplotlib.pyplot as plt

def analyze_and_plot(folder_path, label):
    skewness_values = []
    filenames = []

    for filename in os.listdir(folder_path):
        if filename.endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(folder_path, filename)
            try:
                image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
                if image is None:
                    print(f"Error: Could not read image '{image_path}'. Skipping.")
                    continue

                skewness = skew(image.flatten())
                skewness_values.append(skewness)
                filenames.append(filename)

            except Exception as e:
                print(f"Error processing image '{image_path}': {e}")

    return filenames, skewness_values


# Example usage
clear_filenames, clear_skewness = analyze_and_plot("/content/drive/MyDrive/INDOOR_CLEAR/clear", "Indoor Clear")
hazy_filenames, hazy_skewness = analyze_and_plot("/content/drive/MyDrive/INDOOR_HAZY/hazy", "Indoor Hazy")

# Ensure both lists have the same length for plotting
min_len = min(len(clear_skewness), len(hazy_skewness))
clear_skewness = clear_skewness[:min_len]
hazy_skewness = hazy_skewness[:min_len]
filenames = clear_filenames[:min_len] # Use filenames from clear as a reference


plt.figure(figsize=(12, 6))
plt.plot(filenames, clear_skewness, marker='o', linestyle='-', label='INDOOR_CLEAR')
plt.plot(filenames, hazy_skewness, marker='x', linestyle='-', label='INDOOR_HAZY')

plt.xlabel('Image Filenames')
plt.ylabel('Skewness')
plt.title('Skewness Comparison: INDOOR_CLEAR vs. INDOOR_HAZY')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()

"""line chart of the kurtosis of INDOOR_CLEAR and INDOOR_HAZY"""

# prompt: how to compare line chart between INDOOR_CLEAR AND INDOOR_HAZY all images with ONLY kurtosis with INDOOR_CLEAR AND INDOOR_HAZY with up and down line chart

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis
import matplotlib.pyplot as plt

def analyze_and_plot(folder_path, label):
    kurtosis_values = []
    filenames = []

    for filename in os.listdir(folder_path):
        if filename.endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(folder_path, filename)
            try:
                image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
                if image is None:
                    print(f"Error: Could not read image '{image_path}'. Skipping.")
                    continue

                kurt = kurtosis(image.flatten())
                kurtosis_values.append(kurt)
                filenames.append(filename)

            except Exception as e:
                print(f"Error processing image '{image_path}': {e}")

    return filenames, kurtosis_values

# Example usage
clear_filenames, clear_kurtosis = analyze_and_plot("/content/drive/MyDrive/INDOOR_CLEAR/clear", "Indoor Clear")
hazy_filenames, hazy_kurtosis = analyze_and_plot("/content/drive/MyDrive/INDOOR_HAZY/hazy", "Indoor Hazy")

# Ensure both lists have the same length for plotting
min_len = min(len(clear_kurtosis), len(hazy_kurtosis))
clear_kurtosis = clear_kurtosis[:min_len]
hazy_kurtosis = hazy_kurtosis[:min_len]
filenames = clear_filenames[:min_len] # Use filenames from clear as a reference


plt.figure(figsize=(12, 6))
plt.plot(filenames, clear_kurtosis, marker='o', linestyle='-', label='INDOOR_CLEAR')
plt.plot(filenames, hazy_kurtosis, marker='x', linestyle='-', label='INDOOR_HAZY')

plt.xlabel('Image Filenames')
plt.ylabel('Kurtosis')
plt.title('Kurtosis Comparison: INDOOR_CLEAR vs. INDOOR_HAZY')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()

"""line chart of the skewness of OUTDOOR_CLEAR and OUTDOOR_HAZY"""

# prompt: how to compare line chart between OUTDOOR_CLEAR AND OUTDOOR_HAZY all images with ONLY skewness with INDOOR_CLEAR AND INDOOR_HAZY with up and down line chart

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis
import matplotlib.pyplot as plt

def analyze_and_plot(folder_path, label):
    skewness_values = []
    filenames = []

    for filename in os.listdir(folder_path):
        if filename.endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(folder_path, filename)
            try:
                image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
                if image is None:
                    print(f"Error: Could not read image '{image_path}'. Skipping.")
                    continue

                skewness = skew(image.flatten())
                skewness_values.append(skewness)
                filenames.append(filename)

            except Exception as e:
                print(f"Error processing image '{image_path}': {e}")

    return filenames, skewness_values


# Example usage
clear_filenames, clear_skewness = analyze_and_plot("/content/drive/MyDrive/OUTDOOR_CLEAR/clear", "outdoor Clear")
hazy_filenames, hazy_skewness = analyze_and_plot("/content/drive/MyDrive/OUTDOOR_HAZY/hazy", "outdoor Hazy")

# Ensure both lists have the same length for plotting
min_len = min(len(clear_skewness), len(hazy_skewness))
clear_skewness = clear_skewness[:min_len]
hazy_skewness = hazy_skewness[:min_len]
filenames = clear_filenames[:min_len] # Use filenames from clear as a reference


plt.figure(figsize=(12, 6))
plt.plot(filenames, clear_skewness, marker='o', linestyle='-', label='OUTDOOR_CLEAR')
plt.plot(filenames, hazy_skewness, marker='x', linestyle='-', label='OUTDOOR_HAZY')

plt.xlabel('Image Filenames')
plt.ylabel('Skewness')
plt.title('Skewness Comparison: OUTDOOR_CLEAR vs. OUTDOOR_HAZY')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()

"""line chart of the kurtosis of OUTDOOR_CLEAR and OUTDOOR_HAZY"""

# prompt: how to compare line chart between INDOOR_CLEAR AND INDOOR_HAZY all images with ONLY kurtosis with INDOOR_CLEAR AND INDOOR_HAZY with up and down line chart

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis
import matplotlib.pyplot as plt

def analyze_and_plot(folder_path, label):
    kurtosis_values = []
    filenames = []

    for filename in os.listdir(folder_path):
        if filename.endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(folder_path, filename)
            try:
                image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
                if image is None:
                    print(f"Error: Could not read image '{image_path}'. Skipping.")
                    continue

                kurt = kurtosis(image.flatten())
                kurtosis_values.append(kurt)
                filenames.append(filename)

            except Exception as e:
                print(f"Error processing image '{image_path}': {e}")

    return filenames, kurtosis_values

# Example usage
clear_filenames, clear_kurtosis = analyze_and_plot("/content/drive/MyDrive/OUTDOOR_CLEAR/clear", "outdoor Clear")
hazy_filenames, hazy_kurtosis = analyze_and_plot("/content/drive/MyDrive/OUTDOOR_HAZY/hazy", "outdoor Hazy")

# Ensure both lists have the same length for plotting
min_len = min(len(clear_kurtosis), len(hazy_kurtosis))
clear_kurtosis = clear_kurtosis[:min_len]
hazy_kurtosis = hazy_kurtosis[:min_len]
filenames = clear_filenames[:min_len] # Use filenames from clear as a reference


plt.figure(figsize=(12, 6))
plt.plot(filenames, clear_kurtosis, marker='o', linestyle='-', label='OUTDOOR_CLEAR')
plt.plot(filenames, hazy_kurtosis, marker='x', linestyle='-', label='OUTDOOR_HAZY')

plt.xlabel('Image Filenames')
plt.ylabel('Kurtosis')
plt.title('Kurtosis Comparison: OUTDOOR_CLEAR vs. OUTDOOR_HAZY')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()

"""graph convert into png file

"""

# prompt: how to convert that 4 graph into pdf and it is save on drive with new folder and that 4 graph store in new folder for all 4 graph

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

def analyze_and_plot(folder_path, label1, label2, output_filename):
    """
    Analyzes images in a folder and creates a plot of skewness or kurtosis.
    """

    def extract_features(folder_path):
      filenames = []
      skewness_values = []
      kurtosis_values = []

      for filename in os.listdir(folder_path):
          if filename.endswith(('.jpg', '.jpeg', '.png')):
              image_path = os.path.join(folder_path, filename)
              try:
                  image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
                  if image is None:
                      print(f"Error: Could not read image '{image_path}'. Skipping.")
                      continue
                  skewness = skew(image.flatten())
                  kurt = kurtosis(image.flatten())
                  filenames.append(filename)
                  skewness_values.append(skewness)
                  kurtosis_values.append(kurt)
              except Exception as e:
                  print(f"Error processing image '{image_path}': {e}")
      return filenames, skewness_values, kurtosis_values

    filenames1, skewness1, kurtosis1 = extract_features(folder_path[0])
    filenames2, skewness2, kurtosis2 = extract_features(folder_path[1])

    min_len = min(len(skewness1), len(skewness2))
    filenames = filenames1[:min_len]
    skewness1 = skewness1[:min_len]
    skewness2 = skewness2[:min_len]
    kurtosis1 = kurtosis1[:min_len]
    kurtosis2 = kurtosis2[:min_len]

    # Create plots
    plt.figure(figsize=(12, 6))
    plt.plot(filenames, skewness1, marker='o', linestyle='-', label=label1)
    plt.plot(filenames, skewness2, marker='x', linestyle='-', label=label2)
    plt.xlabel('Image Filenames')
    plt.ylabel('Skewness')
    plt.title(f'Skewness Comparison: {label1} vs. {label2}')
    plt.xticks(rotation=45, ha='right')
    plt.legend()
    plt.tight_layout()

    plt.savefig(output_filename + "_skewness.png") # save figure as png

    plt.figure(figsize=(12, 6))
    plt.plot(filenames, kurtosis1, marker='o', linestyle='-', label=label1)
    plt.plot(filenames, kurtosis2, marker='x', linestyle='-', label=label2)
    plt.xlabel('Image Filenames')
    plt.ylabel('Kurtosis')
    plt.title(f'Kurtosis Comparison: {label1} vs. {label2}')
    plt.xticks(rotation=45, ha='right')
    plt.legend()
    plt.tight_layout()

    plt.savefig(output_filename + "_kurtosis.png") #save figure as png

# Define paths and output folder
output_folder = "/content/drive/MyDrive/image_analysis_results"  # Customize your output folder path
os.makedirs(output_folder, exist_ok=True)

# Create plots
analyze_and_plot(["/content/drive/MyDrive/INDOOR_CLEAR/clear", "/content/drive/MyDrive/INDOOR_HAZY/hazy"], "INDOOR_CLEAR", "INDOOR_HAZY", os.path.join(output_folder, "indoor"))
analyze_and_plot(["/content/drive/MyDrive/OUTDOOR_CLEAR/clear", "/content/drive/MyDrive/OUTDOOR_HAZY/hazy"], "OUTDOOR_CLEAR", "OUTDOOR_HAZY", os.path.join(output_folder, "outdoor"))

# prompt: avg skewness of 4 FOLDER

import os
import cv2
import numpy as np
from scipy.stats import skew
import matplotlib.pyplot as plt

def calculate_average_skewness(folder_path):
  """Calculates the average skewness of images in a folder."""
  skewness_values = []
  for filename in os.listdir(folder_path):
    if filename.endswith(('.jpg', '.jpeg', '.png')):
      image_path = os.path.join(folder_path, filename)
      try:
        image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        if image is None:
          print(f"Error: Could not read image '{image_path}'. Skipping.")
          continue
        skewness = skew(image.flatten())
        skewness_values.append(skewness)
      except Exception as e:
        print(f"Error processing image '{image_path}': {e}")
  if skewness_values:
    return np.mean(skewness_values)
  else:
    return 0  # Return 0 if no valid images are found


# Example usage (replace with your folder paths):
folders = [
    "/content/drive/MyDrive/INDOOR_CLEAR/clear",
    "/content/drive/MyDrive/INDOOR_HAZY/hazy",
    "/content/drive/MyDrive/OUTDOOR_CLEAR/clear",
    "/content/drive/MyDrive/OUTDOOR_HAZY/hazy",
]

total_skewness = 0
for folder in folders:
  avg_skewness = calculate_average_skewness(folder)
  print(f"Average skewness for {folder}: {avg_skewness}")
  total_skewness += avg_skewness

overall_avg_skewness = total_skewness / len(folders)
print(f"\nOverall average skewness across all folders: {overall_avg_skewness}")

# prompt: avg kurtosis of 4 FOLDER

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis

def calculate_average_kurtosis(folder_path):
    """Calculates the average kurtosis of images in a folder."""
    kurtosis_values = []
    for filename in os.listdir(folder_path):
        if filename.endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(folder_path, filename)
            try:
                image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
                if image is None:
                    print(f"Error: Could not read image '{image_path}'. Skipping.")
                    continue
                kurt = kurtosis(image.flatten())
                kurtosis_values.append(kurt)
            except Exception as e:
                print(f"Error processing image '{image_path}': {e}")
    if kurtosis_values:
        return np.mean(kurtosis_values)
    else:
        return 0  # Return 0 if no valid images are found

# Example usage (replace with your folder paths):
folders = [
    "/content/drive/MyDrive/INDOOR_CLEAR/clear",
    "/content/drive/MyDrive/INDOOR_HAZY/hazy",
    "/content/drive/MyDrive/OUTDOOR_CLEAR/clear",
    "/content/drive/MyDrive/OUTDOOR_HAZY/hazy",
]

total_kurtosis = 0
for folder in folders:
    avg_kurtosis = calculate_average_kurtosis(folder)
    print(f"Average kurtosis for {folder}: {avg_kurtosis}")
    total_kurtosis += avg_kurtosis

overall_avg_kurtosis = total_kurtosis / len(folders)
print(f"\nOverall average kurtosis across all folders: {overall_avg_kurtosis}")

import cv2
import numpy as np
import os

# Path to the directory containing the images in Google Drive
image_directory = '/content/drive/MyDrive/INDOOR_CLEAR/clear'

# Initialize a list to hold all pixel values
all_pixel_values = []

# Specify width and height for resizing
width = 224  # Example width
height = 224 # Example height

# Loop through the images in the directory
for filename in os.listdir(image_directory):
    if filename.endswith('.jpg') or filename.endswith('.png'):  # Adjust based on your image formats
        img_path = os.path.join(image_directory, filename)
        img = cv2.imread(img_path)

        if img is not None:
            # Resize images to the same size if necessary
            img = cv2.resize(img, (width, height))  # Specify width and height
            # Flatten the image to a 1D array and extend to all_pixel_values
            all_pixel_values.extend(img.flatten())

# Convert list of all pixel values to a NumPy array
all_pixel_values_array = np.array(all_pixel_values)

# Calculate the overall mean and median of all pixel values
overall_mean = np.mean(all_pixel_values_array)
overall_median = np.median(all_pixel_values_array)

# Print the overall mean and median pixel values
print("Overall Mean Pixel Value:", overall_mean)
print("Overall Median Pixel Value:", overall_median)

import cv2
import numpy as np
import os

# Path to the directory containing the images in Google Drive
image_directory = '/content/drive/MyDrive/INDOOR_HAZY/hazy'

# Initialize a list to hold all pixel values
all_pixel_values = []

# Specify width and height for resizing
width = 224  # Example width
height = 224 # Example height

# Loop through the images in the directory
for filename in os.listdir(image_directory):
    if filename.endswith('.jpg') or filename.endswith('.png'):  # Adjust based on your image formats
        img_path = os.path.join(image_directory, filename)
        img = cv2.imread(img_path)

        if img is not None:
            # Resize images to the same size if necessary
            img = cv2.resize(img, (width, height))  # Specify width and height
            # Flatten the image to a 1D array and extend to all_pixel_values
            all_pixel_values.extend(img.flatten())

# Convert list of all pixel values to a NumPy array
all_pixel_values_array = np.array(all_pixel_values)

# Calculate the overall mean and median of all pixel values
overall_mean = np.mean(all_pixel_values_array)
overall_median = np.median(all_pixel_values_array)

# Print the overall mean and median pixel values
print("Overall Mean Pixel Value:", overall_mean)
print("Overall Median Pixel Value:", overall_median)

import cv2
import numpy as np
import os

# Path to the directory containing the images in Google Drive
image_directory = '/content/drive/MyDrive/OUTDOOR_CLEAR/clear'

# Initialize a list to hold all pixel values
all_pixel_values = []

# Specify width and height for resizing
width = 224  # Example width
height = 224 # Example height

# Loop through the images in the directory
for filename in os.listdir(image_directory):
    if filename.endswith('.jpg') or filename.endswith('.png'):  # Adjust based on your image formats
        img_path = os.path.join(image_directory, filename)
        img = cv2.imread(img_path)

        if img is not None:
            # Resize images to the same size if necessary
            img = cv2.resize(img, (width, height))  # Specify width and height
            # Flatten the image to a 1D array and extend to all_pixel_values
            all_pixel_values.extend(img.flatten())

# Convert list of all pixel values to a NumPy array
all_pixel_values_array = np.array(all_pixel_values)

# Calculate the overall mean and median of all pixel values
overall_mean = np.mean(all_pixel_values_array)
overall_median = np.median(all_pixel_values_array)

# Print the overall mean and median pixel values
print("Overall Mean Pixel Value:", overall_mean)
print("Overall Median Pixel Value:", overall_median)

import cv2
import numpy as np
import os

# Path to the directory containing the images in Google Drive
image_directory = '/content/drive/MyDrive/OUTDOOR_HAZY/hazy'

# Initialize a list to hold all pixel values
all_pixel_values = []

# Specify width and height for resizing
width = 224  # Example width
height = 224 # Example height

# Loop through the images in the directory
for filename in os.listdir(image_directory):
    if filename.endswith('.jpg') or filename.endswith('.png'):  # Adjust based on your image formats
        img_path = os.path.join(image_directory, filename)
        img = cv2.imread(img_path)

        if img is not None:
            # Resize images to the same size if necessary
            img = cv2.resize(img, (width, height))  # Specify width and height
            # Flatten the image to a 1D array and extend to all_pixel_values
            all_pixel_values.extend(img.flatten())

# Convert list of all pixel values to a NumPy array
all_pixel_values_array = np.array(all_pixel_values)

# Calculate the overall mean and median of all pixel values
overall_mean = np.mean(all_pixel_values_array)
overall_median = np.median(all_pixel_values_array)

# Print the overall mean and median pixel values
print("Overall Mean Pixel Value:", overall_mean)
print("Overall Median Pixel Value:", overall_median)

# prompt: find the standard deviation of the 4 folder

import os
import cv2
import numpy as np
from scipy.stats import skew, kurtosis
# ... (rest of your existing code)

def calculate_standard_deviation(folder_path):
    """Calculates the standard deviation of pixel values in images within a folder."""
    pixel_values = []
    for filename in os.listdir(folder_path):
        if filename.endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(folder_path, filename)
            try:
                image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
                if image is None:
                    print(f"Error: Could not read image '{image_path}'. Skipping.")
                    continue
                pixel_values.extend(image.flatten())
            except Exception as e:
                print(f"Error processing image '{image_path}': {e}")
    if pixel_values:
        return np.std(pixel_values)
    else:
        return 0  # Return 0 if no valid images are found

# Example usage:
folders = [
    "/content/drive/MyDrive/INDOOR_CLEAR/clear",
    "/content/drive/MyDrive/INDOOR_HAZY/hazy",
    "/content/drive/MyDrive/OUTDOOR_CLEAR/clear",
    "/content/drive/MyDrive/OUTDOOR_HAZY/hazy",
]

for folder in folders:
    std_dev = calculate_standard_deviation(folder)
    print(f"Standard deviation of pixel values for {folder}: {std_dev}")

# prompt: all above data in tabular form

import pandas as pd

data = {
    'Category': ['INDOOR_CLEAR', 'INDOOR_HAZY', 'OUTDOOR_CLEAR', 'OUTDOOR_HAZY'],
    'Avg_Skewness': [ 0.46,-0.03,0.34,0.24], # Placeholder, replace with actual values
    'Avg_Kurtosis': [-0.48,-0.65,-0.84,-0.84], # Placeholder, replace with actual values
    'Overall_Mean_Pixel': [99.5, 158.09,116.31,151.56], # Placeholder, replace with actual values
    'Overall_Median_Pixel': [89,160,102,146], # Placeholder, replace with actual values
    'Std_Dev_Pixel': [72.90,54.54,74.86,53.07] # Placeholder, replace with actual values

}

df = pd.DataFrame(data)
df